"use client";
import { useRef, useCallback, useState, forwardRef } from 'react';
import HTMLFlipBook from 'react-pageflip';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

// Helper component for pages to ensure refs work with react-pageflip
const Page = forwardRef((props, ref) => {
    return (
        <div className="demoPage bg-white shadow-sm border border-gray-200 h-full overflow-hidden" ref={ref}>
            <div className="relative h-full flex flex-col">
                {props.children}
                <div className="absolute bottom-2 text-[10px] text-gray-400 w-full text-center font-serif">
                    {props.number && `Page ${props.number}`}
                </div>
            </div>
        </div>
    );
});
Page.displayName = 'Page';

export default function ComicDisplay({ comic }) {
    const bookRef = useRef();
    const [isDownloading, setIsDownloading] = useState(false);
    const [pageIndex, setPageIndex] = useState(0);

    if (!comic) return null;

    // Calculate Transform classes for Centering (Desktop Only)
    // Cover (0) is on Right -> Shift Left (-25%) on Desktop
    // End Page (Last) is on Left -> Shift Right (+25%) on Desktop
    const lastIndex = comic.panels.length + 1;
    let transformClass = 'translate-x-0';
    if (pageIndex === 0) transformClass = 'translate-x-0 md:-translate-x-[25%]';
    else if (pageIndex === lastIndex) transformClass = 'translate-x-0 md:translate-x-[25%]';

    // Cover Page
    const coverPage = (
        <div className="h-full flex flex-col items-center justify-center bg-love-50 p-6 border-4 border-love-900/10 text-center relative overflow-hidden">
            <div className="absolute inset-0 opacity-10 bg-[url('https://www.transparenttextures.com/patterns/cream-paper.png')]"></div>
            <div className="z-10 border-4 border-double border-love-800 p-8 py-16 bg-white shadow-xl rotate-1">
                <h1 className="text-4xl md:text-5xl font-serif font-bold text-love-800 mb-4">{comic.title}</h1>
                <div className="w-16 h-1 bg-love-500 mx-auto mb-6"></div>
                <p className="text-gray-500 italic font-serif">A True Story of Love & Magic</p>
                <div className="mt-8 text-xs text- любви-400 uppercase tracking-widest">
                    AI Comic Generator
                </div>
            </div>
        </div>
    );

    // End Page
    const endPage = (
        <div className="h-full flex flex-col items-center justify-center bg-love-900 text-white p-6 relative overflow-hidden">
            <h2 className="text-4xl font-serif font-bold mb-4">The End</h2>
            <p className="text-love-200 italic">...or just the beginning?</p>
            <div className="mt-12 opacity-50 text-6xl">❤️</div>
        </div>
    );

    const downloadPDF = async () => {
        setIsDownloading(true);

        try {
            const doc = new jsPDF('p', 'mm', 'a4');
            const pageWidth = doc.internal.pageSize.getWidth();
            const pageHeight = doc.internal.pageSize.getHeight();

            // Title Page
            doc.setFont("times", "bold");
            doc.setFontSize(24);
            doc.text(comic.title, pageWidth / 2, 40, { align: "center" });
            doc.setFontSize(12);
            doc.setFont("helvetica", "normal");
            doc.text("Generated by AI Comic App", pageWidth / 2, 50, { align: "center" });

            let yPos = 70;

            // Helper to get base64
            const getBase64FromUrl = async (url) => {
                const data = await fetch(url);
                const blob = await data.blob();
                return new Promise((resolve) => {
                    const reader = new FileReader();
                    reader.readAsDataURL(blob);
                    reader.onloadend = () => resolve(reader.result);
                });
            };

            for (let i = 0; i < comic.panels.length; i++) {
                const panel = comic.panels[i];

                // Add new page if needed
                if (yPos > 240) {
                    doc.addPage();
                    yPos = 30;
                }

                try {
                    // Fetch image as data URL to avoid CORS/taint issues in jsPDF
                    const imgData = await getBase64FromUrl(panel.image);

                    // Create dummy image to get dimensions
                    const img = new Image();
                    img.src = imgData;
                    await new Promise(r => img.onload = r);

                    // Calculate dimensions
                    const imgWidth = 150; // slightly smaller margin
                    const imgHeight = (img.naturalHeight / img.naturalWidth) * imgWidth;
                    const xPos = (pageWidth - imgWidth) / 2;

                    doc.addImage(imgData, 'PNG', xPos, yPos, imgWidth, imgHeight);
                    yPos += imgHeight + 10;

                    // Caption
                    doc.setFontSize(10);
                    doc.setTextColor(100);
                    const splitText = doc.splitTextToSize(panel.caption ? panel.caption : "", 150);
                    doc.text(splitText, pageWidth / 2, yPos, { align: 'center' });
                    yPos += (splitText.length * 5) + 15;

                } catch (imgError) {
                    console.error(`Failed to load image for panel ${i + 1}`, imgError);
                    doc.setTextColor(255, 0, 0);
                    doc.text(`[Image Failed to Load]`, pageWidth / 2, yPos, { align: 'center' });
                    yPos += 20;
                }
            }

            doc.save(`${comic.title.replace(/\s+/g, '_')}_Comic.pdf`);

        } catch (e) {
            console.error("PDF Generation Critical Fail", e);
            alert(`PDF Generation Failed: ${e.message}`);
        }
        setIsDownloading(false);
    };

    const handleShare = async () => {
        if (typeof navigator !== 'undefined' && navigator.share) {
            try {
                await navigator.share({
                    title: comic.title,
                    text: `Check out our AI Love Story: ${comic.title}!`,
                    url: window.location.href,
                });
            } catch (err) {
                console.log('Share canceled');
            }
        } else if (typeof navigator !== 'undefined' && navigator.clipboard && navigator.clipboard.writeText) {
            try {
                await navigator.clipboard.writeText(window.location.href);
                alert("Link copied to clipboard! 📋");
            } catch (err) {
                alert("Could not copy link. Is the site on HTTPS?");
            }
        } else {
            alert("Sharing is not supported in this browser environment.");
        }
    };

    return (
        <div className="w-full max-w-full md:max-w-[95vw] lg:max-w-7xl mx-auto animate-fade-in mt-4 md:mt-8 space-y-4 md:space-y-8 pb-12 flex flex-col items-center overflow-x-hidden">

            <div className="text-center space-y-1 md:space-y-2 mb-2 md:mb-4 px-4">
                <span className="text-love-500 font-bold tracking-widest text-[8px] md:text-xs uppercase bg-white px-2 md:px-3 py-1 rounded-full shadow-sm">Interactive Flipbook</span>
                <h2 className="text-xl md:text-4xl font-serif font-bold text-gray-900 leading-tight">
                    {comic.title}
                </h2>
            </div>

            {/* Flipbook Container */}
            <div
                className="relative z-10 w-full h-[50vh] md:h-[85vh] flex justify-center items-center transition-all duration-700 ease-in-out"
            >
                <div
                    className={`relative flex justify-center items-center h-full w-full transition-transform duration-500 ease-out ${transformClass}`}
                >
                    {/* Navigation Arrows - Adjusted for Mobile */}
                    <button
                        onClick={() => bookRef.current.pageFlip().flipPrev()}
                        className="absolute left-1 md:-left-12 top-1/2 -translate-y-1/2 z-20 w-8 h-8 md:w-14 md:h-14 bg-white/60 md:bg-white/80 hover:bg-white text-love-600 rounded-full shadow-lg border border-love-100 flex items-center justify-center transition-transform hover:scale-110 active:scale-95 backdrop-blur-sm"
                        aria-label="Previous Page"
                    >
                        <span className="text-lg md:text-2xl">←</span>
                    </button>

                    <HTMLFlipBook
                        width={400}
                        height={600}
                        size="stretch"
                        minWidth={280}        // Reduced for mobile (spread ~560px, still might be tight, usually switches to portrait if single page)
                        // Actually react-pageflip responsiveness is tricky.
                        // Let's rely on size="stretch" and parent container constraints.
                        maxWidth={800}
                        minHeight={350}
                        maxHeight={1000}
                        maxShadowOpacity={0.5}
                        showCover={true}
                        mobileScrollSupport={true}
                        className="demo-book bg-white shadow-2xl"
                        ref={bookRef}
                        onFlip={(e) => setPageIndex(e.data)}
                    >
                        {/* Cover */}
                        <Page number={0}>{coverPage}</Page>

                        {/* Pages */}
                        {comic.panels.map((panel, idx) => (
                            <Page key={idx} number={idx + 1}>
                                <div className="h-[60%] w-full bg-gray-50 border-b-2 border-gray-100 overflow-hidden relative group">
                                    <img
                                        src={panel.image}
                                        alt={`Panel ${idx + 1}`}
                                        className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
                                        crossOrigin="anonymous"
                                        onError={(e) => {
                                            e.target.onerror = null;
                                            e.target.src = "https://placehold.co/600x400?text=Image+Load+Error";
                                        }}
                                    />
                                    {panel.fallback && (
                                        <span className="absolute top-2 right-2 text-[8px] bg-yellow-200 px-1 rounded">AI Placeholder</span>
                                    )}
                                    <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/cream-paper.png')] opacity-20 pointer-events-none"></div>
                                </div>
                                <div className="h-[40%] p-2 md:p-6 flex flex-col justify-center text-center space-y-1 md:space-y-2 bg-white relative">
                                    <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/cream-paper.png')] opacity-30 pointer-events-none"></div>
                                    <div className="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-1/2 w-5 h-5 md:w-8 md:h-8 bg-white rounded-full border border-gray-200 flex items-center justify-center font-serif text-[8px] md:text-sm text-gray-400 shadow-sm z-10">
                                        {idx + 1}
                                    </div>
                                    <p className="font-serif text-xs md:text-xl text-gray-800 italic leading-relaxed line-clamp-3 md:line-clamp-4 px-1">
                                        "{panel.dialogue}"
                                    </p>
                                    <div className="w-8 md:w-12 h-px bg-love-200 mx-auto"></div>
                                    <p className="text-[8px] md:text-xs text-gray-500 leading-snug px-1 line-clamp-2 md:line-clamp-3">
                                        {panel.caption}
                                    </p>
                                </div>
                            </Page>
                        ))}

                        {/* End */}
                        <Page number={comic.panels.length + 1}>{endPage}</Page>

                    </HTMLFlipBook>

                    <button
                        onClick={() => bookRef.current.pageFlip().flipNext()}
                        className="absolute right-1 md:-right-12 top-1/2 -translate-y-1/2 z-20 w-8 h-8 md:w-14 md:h-14 bg-white/60 md:bg-white/80 hover:bg-white text-love-600 rounded-full shadow-lg border border-love-100 flex items-center justify-center transition-transform hover:scale-110 active:scale-95 backdrop-blur-sm"
                        aria-label="Next Page"
                    >
                        <span className="text-lg md:text-2xl">→</span>
                    </button>
                </div>
            </div>

            <p className="text-gray-400 text-[10px] md:text-sm italic animate-pulse">
                (Click arrows, drag corners, or use arrow keys!)
            </p>

            {/* Actions */}
            <div className="flex flex-col md:flex-row justify-center gap-4 md:gap-6 pt-2 w-full px-4">
                <button
                    onClick={downloadPDF}
                    disabled={isDownloading}
                    className="w-full md:w-auto px-8 py-3 bg-white hover:bg-gray-50 text-gray-800 rounded-full font-bold border border-gray-200 transition shadow-sm hover:shadow-md flex items-center justify-center gap-2"
                >
                    {isDownloading ? (
                        <span className="animate-spin text-xl">↻</span>
                    ) : (
                        <span>⬇</span>
                    )}
                    <span>{isDownloading ? 'Exporting...' : 'Download PDF'}</span>
                </button>
                <button
                    onClick={handleShare}
                    className="w-full md:w-auto px-8 py-3 bg-love-600 hover:bg-love-700 text-white rounded-full font-bold transition shadow-lg hover:shadow-xl shadow-love-500/30 flex items-center justify-center gap-2"
                >
                    <span>❤</span> Share Story
                </button>
            </div>
        </div>
    );
}
